"""add chunk_index to ducument_chunks

Revision ID: 188707f9e9e2
Revises: eff41b8f49e7
Create Date: 2026-03-16 15:09:51.971543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188707f9e9e2'
down_revision: Union[str, Sequence[str], None] = 'eff41b8f49e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
